### PR TITLE
Adds invitation

### PR DESCRIPTION
**Pull request by adbarc92**

### CODE REVIEW

**Review by lincketheo — APPROVED** [review]
Just wanna be wary about race conditions on UPDATE's - same thing happened for friend requests. Easy change though.

**Review by lincketheo — COMMENTED** [review]
Do you think we'll have an occasional cron job to clean up DECLINED invitations or just keep them forever?

**Comment by adbarc92** [comment]
> Do you think we'll have an occasional cron job to clean up DECLINED invitations or just keep them forever?

I'd be inclined toward the former. I think it depends a little bit on how long we're planning to persist events, too. I don't see a reason for everything to be incredibly long-lived

**Comment by adbarc92** [comment]
Removes check preventing users from inviting themselves (for now), adds expirationTimestamp

**Pull request merged**
